import { reactive } from "vue";

export type Locale = "th" | "en";

// ── Translation Dictionary ───────────────────────────────────────────────────
const messages = {
  th: {
    // ── Navbar ──────────────────────────────────────────────────────────────
    nav_activities: "กิจกรรม",
    nav_missions: "ภารกิจ",
    nav_rankings: "อันดับ",
    nav_create_team: "สร้างทีม",
    nav_shop: "ร้านค้า",
    nav_profile: "โปรไฟล์",
    notifications: "การแจ้งเตือน",
    mark_all_read: "อ่านทั้งหมด",
    no_notifications: "ยังไม่มีการแจ้งเตือน",
    new_activities: "กิจกรรมใหม่",
    nav_admin: "แอดมิน",

    // ── Common ───────────────────────────────────────────────────────────────
    loading: "กำลังโหลด...",
    loading_data: "กำลังโหลดข้อมูล...",
    loading_more: "กำลังโหลดเพิ่ม...",
    retry: "ลองใหม่อีกครั้ง",
    back: "ย้อนกลับ",
    confirm: "ยืนยัน",
    cancel: "ยกเลิก",
    save: "บันทึก",
    save_changes: "บันทึกการเปลี่ยนแปลง",
    delete: "ลบ",
    edit: "แก้ไข",
    close: "ปิด",
    search: "ค้นหา",
    submit: "ส่ง",
    send: "ส่ง",
    view_all: "ดูทั้งหมด",
    view_detail: "ดูรายละเอียด",
    all: "ทั้งหมด",
    or: "หรือ",
    yes: "ใช่",
    no: "ไม่",
    accept: "ยอมรับ",
    accept_all: "ยอมรับทั้งหมด",
    acknowledge: "รับทราบและยอมรับ",
    no_data: "ไม่มีข้อมูล",
    not_found: "ไม่พบข้อมูล",
    success: "สำเร็จ",
    failed: "ไม่สำเร็จ",
    points: "คะแนน",
    score: "คะแนน",

    // ── Auth / Login ────────────────────────────────────────────────────────
    login: "เข้าสู่ระบบ",
    login_with_line: "เข้าสู่ระบบด้วย LINE",
    login_loading: "กำลังเข้าสู่ระบบ...",
    logout: "ออกจากระบบ",
    register: "สมัครสมาชิก",
    forgot_password: "ลืมรหัสผ่าน",
    reset_password: "รีเซ็ตรหัสผ่าน",
    email_or_phone: "หมายเลขโทรศัพท์ / Email / ชื่อผู้ใช้",
    email: "อีเมล",
    password: "รหัสผ่าน",
    new_password: "รหัสผ่านใหม่",
    name: "ชื่อ",
    phone: "เบอร์โทรศัพท์",
    hero_desc: "ระบบส่งเสริมกิจกรรมสุขภาพ\\nและติดตามพฤติกรรมสุขภาพของผู้ใช้",

    // PDPA
    pdpa_title: "นโยบายความเป็นส่วนตัว (PDPA)",
    terms_title: "เงื่อนไขการให้บริการ",
    accept_terms: "เงื่อนไขการให้บริการ",
    accept_privacy: "นโยบายความเป็นส่วนตัว (PDPA)",
    pdpa_must_accept:
      "กรุณายอมรับเงื่อนไขการให้บริการและนโยบายความเป็นส่วนตัวก่อนเข้าสู่ระบบ",
    captcha_required: "กรุณายืนยันตัวตน (Captcha) ก่อนเข้าสู่ระบบ",

    // ── Profile ─────────────────────────────────────────────────────────────
    profile: "โปรไฟล์",
    edit_profile: "แก้ไขโปรไฟล์",
    my_score: "คะแนนสะสม",
    my_team: "ทีมของฉัน",
    my_level: "ระดับ",
    total_score: "คะแนนรวม",
    my_rank: "อันดับของฉัน",
    fname: "ชื่อ (ภาษาไทย)",
    lname: "นามสกุล (ภาษาไทย)",
    nickname: "ชื่อเล่น",
    gender: "เพศ",
    birth_date: "วันเกิด",
    gender_male: "ชาย",
    gender_female: "หญิง",
    gender_other: "อื่นๆ",
    weight: "น้ำหนัก (กก.)",
    height: "ส่วนสูง (ซม.)",
    id_code: "รหัสประจำตัว (บัตรประชาชน)",
    address: "ที่อยู่",
    underlying_disease: "โรคประจำตัว",
    main_goal: "เป้าหมายหลัก",
    activity_level: "ระดับการออกกำลังกาย",
    change_photo: "เปลี่ยนรูปโปรไฟล์",
    upload_photo: "อัปโหลดรูปภาพ",
    // ── Profile Tabs & Extras ──
    my_list: "รายการของฉัน",
    // DUPLICATE:     view_all: 'ดูทั้งหมด',
    dashboard_tab: "แดชบอร์ด",
    health_hub: "ภาพรวมสุขภาพ",
    hub_dashboard_desc: "สรุปแต้ม ระยะทาง และความคืบหน้าของคุณ",
    hub_tanita_desc: "น้ำหนัก ไขมัน มวลกล้ามเนื้อ และค่าต่าง ๆ",
    hub_calendar_desc: "ติดตามภารกิจรายวันบนปฏิทิน",
    my_info: "ข้อมูลของฉัน",
    contact_info: "ข้อมูลติดต่อ",
    body_composition: "ข้อมูลองค์ประกอบร่างกาย",
    mission_calendar: "ปฏิทินภารกิจ",
    registered_events: "กิจกรรมที่สมัคร",
    // DUPLICATE:     logout: 'ออกจากระบบ',
    hide_menu: "ซ่อนเมนู",
    show_menu: "แสดงเมนู",
    // DUPLICATE:     edit: 'แก้ไข',
    weight_label: "น้ำหนัก",
    kg: "กก.",
    height_label: "ส่วนสูง",
    cm: "ซม.",
    change_profile_picture: "เปลี่ยนรูปโปรไฟล์",
    day: "วัน",
    month: "เดือน",
    year: "ปี",
    // DUPLICATE:     cancel: 'ยกเลิก',
    // DUPLICATE:     save: 'บันทึก',
    no_underlying_disease: "ไม่มีโรคประจำตัว",
    // DUPLICATE:     no: 'ไม่มี',
    // DUPLICATE:     yes: 'มี',
    specify_underlying_disease: "ระบุโรคประจำตัว",
    // DUPLICATE:     email: 'อีเมล',
    last_update: "อัปเดตล่าสุด:",
    update_body_data: "อัปเดตผลร่างกาย",
    daily_consumption_target: "สรุปเป้าหมายการบริโภครายวัน",
    calorie_recommendation: "คำแนะนำแคลอรี่",
    calorie_target: "เป้าหมายแคลอรี่",
    water_target: "เป้าหมายน้ำดื่ม",
    water_recommendation:
      "ดื่มน้ำช่วยกระตุ้นการเผาผลาญและการไหลเวียนของโลหิต โดยการคำนวณตาม น้ำหนักตัว (กก.) x 30 (มล.) = ปริมาณน้ำที่ควรดื่ม (มิลลิลิตร)",
    protein_target: "เป้าหมายโปรตีน",
    simulate_target: "จำลองเป้าหมายและกิจกรรม",
    simulated_goal: "เป้าหมายจำลอง",
    simulated_activity_level: "ระดับกิจกรรมจำลอง",
    bmi: "ดัชนีมวลกาย (BMI)",
    bmi_under: "ผอม",
    bmi_normal: "ปกติ",
    bmi_over: "ท้วม",
    bmi_obese1: "อ้วน1",
    bmi_obese2: "อ้วน2",
    detailed_body_composition: "องค์ประกอบร่างกายอย่างละเอียด",
    body_weight: "น้ำหนักตัว",
    fat_percentage: "เปอร์เซ็นต์ไขมัน",
    visceral_fat: "ไขมันช่องท้อง",
    level: "ระดับ",
    reduce: "ควรลด",
    total_body_water: "ระดับน้ำในร่างกาย",
    drink_more: "ควรดื่มเพิ่ม",
    muscle_mass: "มวลกล้ามเนื้อ",
    muscle_recommendation:
      "ช่วยกระตุ้นระบบเผาผลาญ ควรออกกำลังกายแรงต้านเพื่อรักษามวลกล้ามเนื้อไว้",
    metabolic_age: "อายุเซลล์",
    metabolic_recommendation:
      "อายุเซลล์ควรเท่ากับหรือน้อยกว่าอายุจริง บ่งบอกสุขภาพการฟื้นฟูของเซลล์ที่ดี",
    no_body_data: "ยังไม่มีข้อมูลองค์ประกอบร่างกาย",
    add_health_data: "เพิ่มข้อมูลสุขภาพ",
    status_full: "เต็มแล้ว",
    status_closed: "ปิดรับสมัคร",
    status_open: "กำลังเปิดรับ",
    points_label: "คะแนน:",
    goal_label: "เป้าหมาย:",
    no_registered_events: "ยังไม่ได้สมัครกิจกรรมใด",
    browse_events: "ดูแคมเปญกิจกรรม",
    search_events: "ค้นหากิจกรรม...",
    show_all_missions: "แสดงภารกิจทั้งหมด",
    your_registered_event: "กิจกรรมที่คุณสมัคร",
    submitted: "ส่งแล้ว",
    due_today: "รอส่งวันนี้",
    missed: "ขาดส่ง",
    not_due_yet: "ยังไม่ถึงกำหนด",
    all_mission_summary: "สรุปการส่งภารกิจทั้งหมด",
    target: "เป้าหมาย",
    no_mission_summary: "ยังไม่มีข้อมูลสรุปภารกิจ",
    edit_health_data: "แก้ไขข้อมูลสุขภาพ",
    save_data: "บันทึกข้อมูล",
    ai_scan: "AI อ่านจากรูป",
    manual_input: "กรอกเอง",
    upload_body_composition_sheet: "อัปโหลดรูปใบวัดองค์ประกอบร่างกาย",
    drop_here: "วางรูปที่นี่",
    supports_drag_drop: "รองรับ drag & drop — AI จะกรอกข้อมูลให้อัตโนมัติ",
    // DUPLICATE:     points: 'คะแนน',
    tdee_ref:
      "คำแนะนำแคลอรี่<br><br><a href='https://www.ptpioneer.com/personal-training/tools/total-daily-energy-expenditure-calculator-tdee-calculator/' target='_blank' class='text-orange-500 font-bold hover:underline'><svg xmlns='http://www.w3.org/2000/svg' width='14' height='14' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round' style='display:inline;vertical-align:-2px;margin-right:4px'><path d='M9 17H7A5 5 0 0 1 7 7h2'/><path d='M15 7h2a5 5 0 1 1 0 10h-2'/><line x1='8' x2='16' y1='12' y2='12'/></svg>อ้างอิงสูตรคำนวณ TDEE & BMR</a>",
    protein_ref:
      "เป้าหมายโปรตีน<br><br><a href='https://www.ironman.com/news/protein-non-negotiable-macro' target='_blank' class='text-blue-500 font-bold hover:underline'><svg xmlns='http://www.w3.org/2000/svg' width='14' height='14' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round' style='display:inline;vertical-align:-2px;margin-right:4px'><path d='M9 17H7A5 5 0 0 1 7 7h2'/><path d='M15 7h2a5 5 0 1 1 0 10h-2'/><line x1='8' x2='16' y1='12' y2='12'/></svg>อ้างอิงเป้าหมายโปรตีนรายวัน</a>",
    // ── Activities ──────────────────────────────────────────────────────────
    activities: "กิจกรรม",
    activity: "กิจกรรม",
    join: "เข้าร่วม",
    joined: "เข้าร่วมแล้ว",
    join_activity: "เข้าร่วมกิจกรรม",
    leave_activity: "ออกจากกิจกรรม",
    participants: "ผู้เข้าร่วม",
    participants_unit: "คน",
    start_date: "วันเริ่ม",
    end_date: "วันสิ้นสุด",
    registration_open: "เปิดรับสมัคร",
    registration_closed: "ปิดรับสมัคร",
    // DUPLICATE:     status_open:        'เปิด',
    // DUPLICATE:     status_closed:      'ปิด',
    status_upcoming: "เร็วๆ นี้",
    status_completed: "เสร็จสิ้น",
    no_activities: "ยังไม่มีกิจกรรม",
    search_activities: "ค้นหากิจกรรม...",
    event_detail: "รายละเอียดกิจกรรม",
    event_goal: "เป้าหมาย",
    event_reward: "รางวัล",
    activities_for_you: "กิจกรรมแนะนำสำหรับคุณ",
    search_results: "ผลการค้นหา",
    no_results_found: "ไม่พบกิจกรรมที่ระบุ",
    my_activities: "กิจกรรมของฉัน",
    ending_soon: "ใกล้ปิดรับสมัคร",
    popular_activities: "กิจกรรมยอดนิยม",
    newest_activities: "มาใหม่ล่าสุด",
    solo_activities: "กิจกรรมแบบคนเดียว",
    team_activities: "กิจกรรมแบบทีม",
    ongoing_activities: "กิจกรรมที่กำลังดำเนินการอยู่",
    active_filters: "ตัวกรองที่เลือกไว้",
    clear_all: "ล้างทั้งหมด",
    no_banner_title: "ไม่พบหัวข้อแบนเนอร์",
    always_open: "เปิดรับตลอด",
    reg_open_forever: "ต่อเนื่องตลอด",
    register_label: "รับสมัคร:",
    activity_date_label: "จัดกิจกรรม:",
    register_always_open_label: "เปิดรับสมัครตลอด",
    register_open_label: "เปิดรับสมัคร:",
    register_close_label: "ปิดรับสมัคร:",
    joined_label: "เข้าร่วมแล้ว",
    unlimited_slots: "รับจำนวนไม่จำกัด",
    not_specified: "ไม่ระบุ",
    unlimited: "ไม่จำกัด",
    loading_activities: "กำลังโหลดกิจกรรมเพิ่ม...",
    no_search_results: "ไม่พบกิจกรรมที่ค้นหา",
    try_change_search: "ลองเปลี่ยนคำค้นหา หรือลดตัวกรองลงนะ",
    sort_label: "เรียงตาม:",
    items_unit: "รายการ",
    status_ended: "สิ้นสุดกิจกรรม",
    status_ongoing: "กำลังดำเนินการ",
    status_registered: "ลงทะเบียนแล้ว",
    // DUPLICATE:     status_full:         'กิจกรรมเต็มแล้ว',

    // ── Missions ─────────────────────────────────────────────────────────────
    missions: "ภารกิจ",
    mission: "ภารกิจ",
    submit_proof: "ส่งหลักฐาน",
    upload_proof: "อัปโหลดหลักฐาน",
    pending: "รอการอนุมัติ",
    approved: "อนุมัติแล้ว",
    rejected: "ไม่ผ่าน",
    daily_mission: "ภารกิจประจำวัน",
    streak: "วันติดต่อกัน",
    streak_days: "วันติดต่อกัน",
    mission_history: "ประวัติการส่งภารกิจ",
    recent_submissions: "รายการล่าสุด",
    select_language: "เลือกภาษา",
    mission_today: "ภารกิจวันนี้",
    mission_completed: "ทำสำเร็จแล้ว",
    mission_pending_review: "รอตรวจสอบ",
    no_missions: "ไม่มีภารกิจในขณะนี้",
    proof_image: "รูปหลักฐาน",
    proof_text: "ข้อความหลักฐาน",
    comment: "ความคิดเห็น",
    admin_comment: "ความคิดเห็นจากแอดมิน",

    // ── Rankings ─────────────────────────────────────────────────────────────
    rankings: "อันดับ",
    rank: "อันดับ",
    rank_col: "อันดับ",
    individual: "รายบุคคล",
    team: "ทีม",
    rank_individual: "อันดับบุคคล",
    rank_team: "อันดับทีม",
    rank_filter_org: "ประเภทผู้ใช้",
    rank_filter_dept: "แผนก",
    rank_filter_role_type: "ประเภทผู้ใช้",
    rank_filter_faculty: "คณะ/สำนักวิชา",
    rank_filter_year: "ชั้นปี",
    rank_filter_clear: "ล้างตัวกรอง",
    rank_overall: "อันดับรวมทั้งหมด",
    rank_subtitle: "แข่งขันกับเพื่อนๆ และทำลายสถิติของตัวคุณเอง",
    rank_no_data: "ยังไม่มีข้อมูลในกิจกรรมนี้",
    rank_username: "ชื่อผู้ใช้งาน",
    rank_teamname: "ชื่อทีม",
    search_activity: "ค้นหากิจกรรม...",
    no_activity_found: "ไม่พบกิจกรรม",
    challenge_activity: "กิจกรรมท้าทาย",

    // ── Teams ────────────────────────────────────────────────────────────────
    teams: "ทีม",
    create_team: "สร้างทีม",
    join_team: "เข้าร่วมทีม",
    leave_team: "ออกจากทีม",
    team_name: "ชื่อทีม",
    team_members: "สมาชิก",
    team_captain: "หัวหน้าทีม",
    team_code: "รหัสทีม",
    invite_member: "เชิญสมาชิก",
    kick_member: "เตะสมาชิก",
    no_team: "ยังไม่มีทีม",
    my_team_members: "สมาชิกในทีม",

    // ── Admin ─────────────────────────────────────────────────────────────────
    admin: "ผู้ดูแลระบบ",
    admin_dashboard: "แดชบอร์ดแอดมิน",
    manage_users: "จัดการผู้ใช้",
    manage_activities: "จัดการกิจกรรม",
    manage_missions: "จัดการภารกิจ",
    manage_teams: "จัดการทีม",
    approve: "อนุมัติ",
    reject: "ปฏิเสธ",
    ban_user: "แบนผู้ใช้",
    unban_user: "ยกเลิกแบน",
    export_excel: "ส่งออก Excel",
    audit_log: "ประวัติการทำงาน",
    total_users: "ผู้ใช้ทั้งหมด",
    total_activities: "กิจกรรมทั้งหมด",
    total_submissions: "การส่งทั้งหมด",

    // ── Errors / Alerts ───────────────────────────────────────────────────────
    error_title: "เกิดข้อผิดพลาด",
    error_connect: "ไม่สามารถเชื่อมต่อเซิร์ฟเวอร์ได้ กรุณาลองใหม่อีกครั้ง",
    session_expired: "เซสชันหมดอายุ",
    forbidden: "คุณไม่มีสิทธิ์เข้าถึง",
    something_wrong: "มีบางอย่างผิดพลาด",
    try_again: "กรุณาลองใหม่อีกครั้ง",

    // ── Body Composition ──────────────────────────────────────────────────────
    // DUPLICATE:     body_composition:   'ข้อมูลองค์ประกอบร่างกาย',
    // DUPLICATE:     bmi:                'ดัชนีมวลกาย (BMI)',
    body_fat: "ไขมันในร่างกาย",
    // DUPLICATE:     muscle_mass:        'มวลกล้ามเนื้อ',
    bone_mass: "มวลกระดูก",
    // DUPLICATE:     metabolic_age:      'อายุเมตาบอลิก',
    // DUPLICATE:     visceral_fat:       'ไขมันในช่องท้อง',
    bmr: "อัตราการเผาผลาญพื้นฐาน",
    ideal_weight: "น้ำหนักที่เหมาะสม",
    scan_tanita: "สแกนข้อมูล Tanita",

    // ── Health ────────────────────────────────────────────────────────────────
    health: "สุขภาพ",
    health_assessment: "การประเมินสุขภาพ",
    health_history: "ประวัติสุขภาพ",
    assessment_result: "ผลการประเมิน",
    health_level: "ระดับสุขภาพ",

    // ── Register / Signup ─────────────────────────────────────────────────────
    signup: "ลงทะเบียน",
    complete_profile: "กรอกข้อมูลโปรไฟล์",
    required_field: "กรุณากรอกข้อมูลที่จำเป็น",
    next_step: "ขั้นตอนต่อไป",
    prev_step: "ย้อนกลับ",
    finish: "เสร็จสิ้น",
  },

  en: {
    // ── Navbar ──────────────────────────────────────────────────────────────
    nav_activities: "Activities",
    nav_missions: "Missions",
    nav_rankings: "Rankings",
    nav_create_team: "Create Team",
    nav_shop: "Shop",
    nav_profile: "Profile",
    notifications: "Notifications",
    mark_all_read: "Mark all read",
    no_notifications: "No notifications yet",
    new_activities: "New activities",
    nav_admin: "Admin",

    // ── Common ───────────────────────────────────────────────────────────────
    loading: "Loading...",
    loading_data: "Loading data...",
    loading_more: "Loading more...",
    retry: "Try Again",
    back: "Back",
    confirm: "Confirm",
    cancel: "Cancel",
    save: "Save",
    save_changes: "Save Changes",
    delete: "Delete",
    edit: "Edit",
    close: "Close",
    search: "Search",
    submit: "Submit",
    send: "Send",
    view_all: "View All",
    view_detail: "View Detail",
    all: "All",
    or: "or",
    yes: "Yes",
    no: "No",
    accept: "Accept",
    accept_all: "Accept All",
    acknowledge: "Acknowledge & Accept",
    no_data: "No data available",
    not_found: "Not Found",
    success: "Success",
    failed: "Failed",
    points: "pts",
    score: "Score",

    // ── Auth / Login ────────────────────────────────────────────────────────
    login: "Login",
    login_with_line: "Login with LINE",
    login_loading: "Logging in...",
    logout: "Logout",
    register: "Register",
    forgot_password: "Forgot Password",
    reset_password: "Reset Password",
    email_or_phone: "Phone / Email / Username",
    email: "Email",
    password: "Password",
    new_password: "New Password",
    name: "Name",
    phone: "Phone",
    hero_desc:
      "Health Activity Promotion System\\nand User Health Behavior Tracking",

    // PDPA
    pdpa_title: "Privacy Policy (PDPA)",
    terms_title: "Terms of Service",
    accept_terms: "Terms of Service",
    accept_privacy: "Privacy Policy (PDPA)",
    pdpa_must_accept:
      "Please accept the Terms of Service and Privacy Policy before logging in.",
    captcha_required:
      "Please complete the CAPTCHA verification before logging in.",

    // ── Profile ─────────────────────────────────────────────────────────────
    profile: "Profile",
    edit_profile: "Edit Profile",
    my_score: "My Score",
    my_team: "My Team",
    my_level: "Level",
    total_score: "Total Score",
    my_rank: "My Rank",
    fname: "First Name (Thai)",
    lname: "Last Name (Thai)",
    nickname: "Nickname",
    gender: "Gender",
    birth_date: "Date of Birth",
    gender_male: "Male",
    gender_female: "Female",
    gender_other: "Other",
    weight: "Weight (kg)",
    height: "Height (cm)",
    id_code: "ID Card Number",
    address: "Address",
    underlying_disease: "Underlying Disease",
    main_goal: "Main Goal",
    activity_level: "Activity Level",
    change_photo: "Change Profile Photo",
    upload_photo: "Upload Photo",
    // ── Profile Tabs & Extras ──
    my_list: "My List",
    // DUPLICATE:     view_all: 'View All',
    dashboard_tab: "Dashboard",
    health_hub: "Health Hub",
    hub_dashboard_desc: "Your points, distance and progress at a glance",
    hub_tanita_desc: "Weight, fat, muscle mass and more",
    hub_calendar_desc: "Track your daily missions on the calendar",
    my_info: "My Info",
    contact_info: "Contact Info",
    body_composition: "Body Composition",
    mission_calendar: "Mission Calendar",
    registered_events: "Registered Events",
    // DUPLICATE:     logout: 'Log Out',
    hide_menu: "Hide Menu",
    show_menu: "Show Menu",
    // DUPLICATE:     edit: 'Edit',
    weight_label: "Weight",
    kg: "kg",
    height_label: "Height",
    cm: "cm",
    change_profile_picture: "Change Profile Picture",
    day: "Day",
    month: "Month",
    year: "Year",
    // DUPLICATE:     cancel: 'Cancel',
    // DUPLICATE:     save: 'Save',
    no_underlying_disease: "No underlying disease",
    // DUPLICATE:     no: 'No',
    // DUPLICATE:     yes: 'Yes',
    specify_underlying_disease: "Specify underlying disease",
    // DUPLICATE:     email: 'Email',
    last_update: "Last Update:",
    update_body_data: "Update Body Data",
    daily_consumption_target: "Daily Consumption Target",
    calorie_recommendation: "Calorie Recommendation",
    calorie_target: "Calorie Target",
    water_target: "Water Target",
    water_recommendation:
      "Drinking water boosts metabolism. Formula: Weight (kg) x 30 = Target (ml)",
    protein_target: "Protein Target",
    simulate_target: "Simulate Target and Activity",
    simulated_goal: "Simulated Goal",
    simulated_activity_level: "Simulated Activity Level",
    bmi: "Body Mass Index (BMI)",
    bmi_under: "Under",
    bmi_normal: "Normal",
    bmi_over: "Over",
    bmi_obese1: "Obese1",
    bmi_obese2: "Obese2",
    detailed_body_composition: "Detailed Body Composition",
    body_weight: "Body Weight",
    fat_percentage: "Fat Percentage",
    visceral_fat: "Visceral Fat",
    level: "Level",
    reduce: "Reduce",
    total_body_water: "Total Body Water",
    drink_more: "Drink More",
    muscle_mass: "Muscle Mass",
    muscle_recommendation:
      "Boosts metabolism. Resistance training helps maintain muscle mass.",
    metabolic_age: "Metabolic Age",
    metabolic_recommendation:
      "Should be less than or equal to actual age. Indicates good cellular recovery.",
    no_body_data: "No body composition data yet",
    add_health_data: "Add Health Data",
    status_full: "Full",
    status_closed: "Closed",
    status_open: "Open",
    points_label: "Points:",
    goal_label: "Goal:",
    no_registered_events: "No events registered yet",
    browse_events: "Browse Events",
    search_events: "Search events...",
    show_all_missions: "Show All Missions",
    your_registered_event: "Your registered event",
    submitted: "Submitted",
    due_today: "Due Today",
    missed: "Missed",
    not_due_yet: "Not Due Yet",
    all_mission_summary: "All Mission Summary",
    target: "Target",
    no_mission_summary: "No mission summary yet",
    edit_health_data: "Edit Health Data",
    save_data: "Save Data",
    ai_scan: "AI Scan",
    manual_input: "Manual",
    upload_body_composition_sheet: "Upload body composition sheet",
    drop_here: "Drop here",
    supports_drag_drop: "Supports drag & drop — AI fills data automatically",
    // DUPLICATE:     points: 'Points',
    tdee_ref:
      "Calorie Recommendation<br><br><a href='https://www.ptpioneer.com/personal-training/tools/total-daily-energy-expenditure-calculator-tdee-calculator/' target='_blank' class='text-orange-500 font-bold hover:underline'><svg xmlns='http://www.w3.org/2000/svg' width='14' height='14' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round' style='display:inline;vertical-align:-2px;margin-right:4px'><path d='M9 17H7A5 5 0 0 1 7 7h2'/><path d='M15 7h2a5 5 0 1 1 0 10h-2'/><line x1='8' x2='16' y1='12' y2='12'/></svg>TDEE & BMR Formula Reference</a>",
    protein_ref:
      "Protein Target<br><br><a href='https://www.ironman.com/news/protein-non-negotiable-macro' target='_blank' class='text-blue-500 font-bold hover:underline'><svg xmlns='http://www.w3.org/2000/svg' width='14' height='14' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round' style='display:inline;vertical-align:-2px;margin-right:4px'><path d='M9 17H7A5 5 0 0 1 7 7h2'/><path d='M15 7h2a5 5 0 1 1 0 10h-2'/><line x1='8' x2='16' y1='12' y2='12'/></svg>Daily Protein Target Reference</a>",
    // ── Activities ──────────────────────────────────────────────────────────
    activities: "Activities",
    activity: "Activity",
    join: "Join",
    joined: "Joined",
    join_activity: "Join Activity",
    leave_activity: "Leave Activity",
    participants: "Participants",
    participants_unit: "people",
    start_date: "Start Date",
    end_date: "End Date",
    registration_open: "Registration Open",
    registration_closed: "Registration Closed",
    // DUPLICATE:     status_open:        'Open',
    // DUPLICATE:     status_closed:      'Closed',
    status_upcoming: "Upcoming",
    status_completed: "Completed",
    no_activities: "No activities yet",
    search_activities: "Search activities...",
    event_detail: "Activity Details",
    event_goal: "Goal",
    event_reward: "Reward",
    activities_for_you: "Recommended for You",
    search_results: "Search Results",
    no_results_found: "No activities found",
    my_activities: "My Activities",
    ending_soon: "Ending Soon",
    popular_activities: "Popular Activities",
    newest_activities: "Newest",
    solo_activities: "Solo Activities",
    team_activities: "Team Activities",
    ongoing_activities: "Ongoing Activities",
    active_filters: "Active Filters",
    clear_all: "Clear All",
    no_banner_title: "No banner title",
    always_open: "Always Open",
    reg_open_forever: "Ongoing",
    register_label: "Register:",
    activity_date_label: "Activity:",
    register_always_open_label: "Registration always open",
    register_open_label: "Opens:",
    register_close_label: "Closes:",
    joined_label: "Joined",
    unlimited_slots: "Unlimited slots",
    not_specified: "N/A",
    unlimited: "unlimited",
    loading_activities: "Loading more activities...",
    no_search_results: "No activities found",
    try_change_search: "Try changing your search or reducing filters.",
    sort_label: "Sort:",
    items_unit: "items",
    status_ended: "Ended",
    status_ongoing: "Ongoing",
    status_registered: "Registered",
    // DUPLICATE:     status_full:         'Full',

    // ── Missions ─────────────────────────────────────────────────────────────
    missions: "Missions",
    mission: "Mission",
    submit_proof: "Submit Proof",
    upload_proof: "Upload Proof",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    daily_mission: "Daily Mission",
    streak: "Day Streak",
    streak_days: "day streak",
    mission_history: "Submission History",
    recent_submissions: "Recent activity",
    select_language: "Select Language",
    mission_today: "Today's Mission",
    mission_completed: "Completed",
    mission_pending_review: "Under Review",
    no_missions: "No missions available",
    proof_image: "Proof Image",
    proof_text: "Proof Text",
    comment: "Comment",
    admin_comment: "Admin Comment",

    // ── Rankings ─────────────────────────────────────────────────────────────
    rankings: "Rankings",
    rank: "Rank",
    rank_col: "Rank",
    individual: "Individual",
    team: "Team",
    rank_individual: "Individual Rankings",
    rank_team: "Team Rankings",
    rank_filter_org: "User type",
    rank_filter_dept: "Department",
    rank_filter_role_type: "User type",
    rank_filter_faculty: "Faculty",
    rank_filter_year: "Year",
    rank_filter_clear: "Clear filters",
    rank_overall: "Overall Rankings",
    rank_subtitle: "Compete with friends and break your own records",
    rank_no_data: "No data for this activity yet",
    rank_username: "Username",
    rank_teamname: "Team Name",
    search_activity: "Search activities...",
    no_activity_found: "No activities found",
    challenge_activity: "Challenge Activity",

    // ── Teams ────────────────────────────────────────────────────────────────
    teams: "Teams",
    create_team: "Create Team",
    join_team: "Join Team",
    leave_team: "Leave Team",
    team_name: "Team Name",
    team_members: "Members",
    team_captain: "Team Captain",
    team_code: "Team Code",
    invite_member: "Invite Member",
    kick_member: "Kick Member",
    no_team: "No team yet",
    my_team_members: "Team Members",

    // ── Admin ─────────────────────────────────────────────────────────────────
    admin: "Administrator",
    admin_dashboard: "Admin Dashboard",
    manage_users: "Manage Users",
    manage_activities: "Manage Activities",
    manage_missions: "Manage Missions",
    manage_teams: "Manage Teams",
    approve: "Approve",
    reject: "Reject",
    ban_user: "Ban User",
    unban_user: "Unban User",
    export_excel: "Export Excel",
    audit_log: "Audit Log",
    total_users: "Total Users",
    total_activities: "Total Activities",
    total_submissions: "Total Submissions",

    // ── Errors / Alerts ───────────────────────────────────────────────────────
    error_title: "An Error Occurred",
    error_connect: "Cannot connect to server. Please try again.",
    session_expired: "Session Expired",
    forbidden: "Access Denied",
    something_wrong: "Something went wrong",
    try_again: "Please try again",

    // ── Body Composition ──────────────────────────────────────────────────────
    // DUPLICATE:     body_composition:   'Body Composition Data',
    // DUPLICATE:     bmi:                'Body Mass Index (BMI)',
    body_fat: "Body Fat",
    // DUPLICATE:     muscle_mass:        'Muscle Mass',
    bone_mass: "Bone Mass",
    // DUPLICATE:     metabolic_age:      'Metabolic Age',
    // DUPLICATE:     visceral_fat:       'Visceral Fat',
    bmr: "Basal Metabolic Rate",
    ideal_weight: "Ideal Weight",
    scan_tanita: "Scan Tanita Data",

    // ── Health ────────────────────────────────────────────────────────────────
    health: "Health",
    health_assessment: "Health Assessment",
    health_history: "Health History",
    assessment_result: "Assessment Result",
    health_level: "Health Level",

    // ── Register / Signup ─────────────────────────────────────────────────────
    signup: "Sign Up",
    complete_profile: "Complete Your Profile",
    required_field: "Please fill in all required fields",
    next_step: "Next",
    prev_step: "Back",
    finish: "Finish",
  },
} as const;

export type MessageKey = keyof typeof messages.th;

// ── Reactive State ───────────────────────────────────────────────────────────
const STORAGE_KEY = "vc_locale";

function detectLocale(): Locale {
  const saved = localStorage.getItem(STORAGE_KEY) as Locale | null;
  if (saved === "th" || saved === "en") return saved;
  return navigator.language.startsWith("th") ? "th" : "en";
}

// อัปเดต <html lang="..."> ให้ตรงกับภาษาที่ใช้งานจริง
// เพื่อให้ browser/WebView เลือก font-shaping ที่ถูกต้องสำหรับแต่ละภาษา
// (ไทยต้องได้ lang="th" ไม่งั้นสระ/วรรณยุกต์บางเครื่องจะเรียงผิดตำแหน่ง)
function applyDocumentLang(locale: Locale) {
  if (typeof document !== "undefined") {
    document.documentElement.lang = locale;
  }
}

export const langStore = reactive({
  locale: "th" as Locale,

  init() {
    this.locale = detectLocale();
    applyDocumentLang(this.locale);
  },

  toggle() {
    this.locale = this.locale === "th" ? "en" : "th";
    localStorage.setItem(STORAGE_KEY, this.locale);
    applyDocumentLang(this.locale);
  },

  setLocale(locale: Locale) {
    this.locale = locale;
    localStorage.setItem(STORAGE_KEY, locale);
    applyDocumentLang(this.locale);
  },

  /** Translate a key — reactive because `this.locale` is tracked */
  t(key: MessageKey): string {
    return (
      (messages[this.locale] as any)[key] ?? (messages.th as any)[key] ?? key
    );
  },
});

/** Composable shorthand */
export function useLang() {
  return langStore;
}
