import express from "express";
import { pool } from "../mysql.js";
import { invalidateScoringCache } from "../lib/scoring.js";

const router = express.Router();

import { requireAdmin } from "../middleware/auth.js";

// 1. Get all active configs
router.get("/", async (req, res) => {
  try {
    const [rows] = await pool.query(
      "SELECT * FROM master_configs WHERE is_active = true ORDER BY sort_order ASC",
    );

    res.json(rows);
  } catch (error: any) {
    res.status(500).json({ error: "Internal Server Error" });
  }
});

// 2. Get by category
router.get("/:category", async (req, res) => {
  try {
    const [rows] = await pool.query(
      "SELECT * FROM master_configs WHERE category = ? AND is_active = true ORDER BY sort_order ASC",
      [req.params.category],
    );

    res.json(rows);
  } catch (error: any) {
    res.status(500).json({ error: "Internal Server Error" });
  }
});

// 3. Admin: Create/Update (Management)
router.post("/", requireAdmin, async (req, res) => {
  const items = Array.isArray(req.body) ? req.body : [req.body];

  try {
    const results = [];
    for (const i of items) {
      // MySQL INSERT ... ON DUPLICATE KEY UPDATE
      const id = i.id || crypto.randomUUID(); // Optional: You might need to import crypto if generating new valid UUIDs here, or let MySQL DEFAULT handle it. Since we define ID as VARCHAR(36) in schema we should generate it if not provided. Or we can rely on UUID() default if MySQL allows it on replace. Wait, MySQL doesn't natively do automatic UUID() for VARCHAR primary keys on standard inserts easily without triggers. Let's supply one if missing.
      // Actually `id` is generated by `UUID()` default in MySQL schema, so if we don't pass it, it creates one. But with ON DUPLICATE KEY UPDATE using UUID() in VALUES is tricky, let's just insert/update manually using the provided id or letting it insert.
      // To precisely mimic Supabase upsert on `category,key_name`, we do:

      const metadataStr = i.metadata ? JSON.stringify(i.metadata) : "{}";

      // We'll execute an UPSERT using the unique constraint `UNIQUE(category, key_name)`
      await pool.query(
        `INSERT INTO master_configs (id, category, key_name, display_label, metadata, sort_order, is_active)
          VALUES (UUID(), ?, ?, ?, ?, ?, ?)
          ON DUPLICATE KEY UPDATE 
          display_label = VALUES(display_label), 
          metadata = VALUES(metadata), 
          sort_order = VALUES(sort_order), 
          is_active = VALUES(is_active)`,
        [
          i.category,
          i.key_name,
          i.display_label,
          metadataStr,
          i.sort_order || 0,
          i.is_active !== false,
        ],
      );
      results.push(i); // Approximate response
    }

    // Refresh scoring engine cache if scoring rules changed.
    if (items.some((i: any) => i.category === "scoring")) {
      invalidateScoringCache();
    }

    res.json(results);
  } catch (error: any) {
    console.error("[ERROR] Master Config Update Failed:", error);
    res.status(400).json({ error: "Bad Request" });
  }
});

// 4. Admin: Soft Delete/Disable
router.patch("/:id/toggle", requireAdmin, async (req, res) => {
  try {
    const { is_active } = req.body;
    await pool.query("UPDATE master_configs SET is_active = ? WHERE id = ?", [
      is_active,
      req.params.id,
    ]);

    // Fetch and return the updated record
    const [rows]: any = await pool.query(
      "SELECT * FROM master_configs WHERE id = ?",
      [req.params.id],
    );
    res.json(rows[0] || {});
  } catch (error: any) {
    res.status(400).json({ error: "Bad Request" });
  }
});

export default router;
